[Ability Switch]

#Test mode, default is False
test = False

#Logging writing to file, default is True
logging = True

#Add Voicechat commands, default is True
voicechat = True

#Suggest voicechat commands to voicechat user, default is True
voice_suggest = True

#use selenium to correct twitterpost etc, default is True
selenium = True

#number of voice clients. It must be same with length of voice_clients_id in Clients section.
voice_clients = 5

[Clients]

main_token = DISCORD_TOKEN

test_token = TEST_DISCORD_TOKEN

voice_clients_id = [1321765242489016340, 1322054520364208231, 1322063853231804426, 1322066754171834480, 1322067201972375664]